# Dependencies


# Permalinks
permalink:        pretty

# Setup
title:            Functional Genomics
tagline:          'Pipeline and code for genomic analysis'
description:      'Pipeline for genomic analysis with relevance to psychiatric disease'
url:              https://mgandal.github.io/hyde
baseurl:          /hyde/

author:
  name:           'Mike Gandal'
  url:            https://twitter.com/mikejg84

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://mgandal.github.com/hyde
